# Generated by Django 2.2.6 on 2019-10-14 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
